package hub.nishat.net.model.VO.HR;

import java.sql.ResultSet;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 22 14:42:08 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_LeaveReportHRImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public VO_LeaveReportHRImpl()
  {
  }

  /**
   * Returns the bind variable value for userId.
   * @return bind variable value for userId
   */
  public String getuserId()
  {
    return (String) getNamedWhereClauseParam("userId");
  }

  /**
   * Sets <code>value</code> for bind variable userId.
   * @param value value to bind as userId
   */
  public void setuserId(String value)
  {
    setNamedWhereClauseParam("userId", value);
  }

  /**
   * executeQueryForCollection - overridden for custom java data source support.
   */
  protected void executeQueryForCollection(Object qc, Object[] params,
                                           int noUserParams)
  {
    super.executeQueryForCollection(qc, params, noUserParams);
  }

  /**
   * hasNextForCollection - overridden for custom java data source support.
   */
  protected boolean hasNextForCollection(Object qc)
  {
    boolean bRet = super.hasNextForCollection(qc);
    return bRet;
  }

  /**
   * createRowFromResultSet - overridden for custom java data source support.
   */
  protected ViewRowImpl createRowFromResultSet(Object qc,
                                               ResultSet resultSet)
  {
    ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
    return value;
  }

  /**
   * getQueryHitCount - overridden for custom java data source support.
   */
  public long getQueryHitCount(ViewRowSetImpl viewRowSet)
  {
    long value = super.getQueryHitCount(viewRowSet);
    return value;
  }
}
