package hub.nishat.net.model.VO.SystemAdmin;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 12 10:19:21 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_AdminConsumedLeavesImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public VO_AdminConsumedLeavesImpl()
  {
  }
}
