package hub.nishat.net.model.VO.Lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 11 11:31:35 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeLovImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public EmployeeLovImpl()
  {
  }
}
