package hub.nishat.net.model.AM.client;

import hub.nishat.net.model.AM.common.HubModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 22 16:33:36 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HubModuleClient
  extends ApplicationModuleImpl
  implements HubModule
{
  /**
   * This is the default constructor (do not remove).
   */
  public HubModuleClient()
  {
  }

  public void refreshVO()
  {
    Object _ret = this.riInvokeExportedMethod(this,"refreshVO",null,null);
    return;
  }
}
