package hub.nishat.net.model.VO;

import oracle.jbo.server.ViewObjectImpl;

import view.nishat.net.Helper.CommonUtil;
import view.nishat.net.Helper.Constants;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 30 12:51:44 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_LcfRequestsImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public VO_LcfRequestsImpl()
  {
  }

  public String getSessionUserId()
  {
    return CommonUtil.getSessionValue(Constants.SESSION_USERID).toString();
  }
  /**
   * Returns the bind variable value for user_id.
   * @return bind variable value for user_id
   */
  public String getuser_id()
  {
    return (String) getNamedWhereClauseParam("user_id");
  }

  /**
   * Sets <code>value</code> for bind variable user_id.
   * @param value value to bind as user_id
   */
  public void setuser_id(String value)
  {
    setNamedWhereClauseParam("user_id", value);
  }
}
