package hub.nishat.net.model.VO;

import oracle.jbo.server.ViewObjectImpl;

import view.nishat.net.Helper.CommonUtil;
import view.nishat.net.Helper.Constants;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 29 16:41:40 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_LfaRequestsImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public VO_LfaRequestsImpl()
  {
  }
  
  public String getSessionUserId()
  {
    return CommonUtil.getSessionValue(Constants.SESSION_USERID).toString();
  }
}
