package hub.nishat.net.model.AM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 22 16:33:36 PKT 2016
// ---------------------------------------------------------------------
public interface HubModule
  extends ApplicationModule
{
  void refreshVO();
}
